coffee(Decaffein)
coffee(Caffein)
syrup(Chocolate)
syrup(Vanila)
syrup(Caramel)
milk(NormalMilk)
milk(LowFatMilk)
milk(NonFatMilk)
milk(NonLactoseMilk)
drink(latte).
drink(cappuccino).
drink(mocha).
drink(americano).
drink(esspresso).
drinK(caramel_mac).
