coffee(decaffein)
coffee(caffein)
syrup(chocolate)
syrup(vanila)
syrup(caramel)
milk(normalMilk)
milk(lowFatMilk)
milk(nonFatMilk)
milk(nonLactoseMilk)
drink(latte).
drink(cappuccino).
drink(mocha).
drink(americano).
drink(esspresso).
drinK(caramel_mac).
