Coffee(Decaffein)
Coffee(Caffein)
Syrup(Chocolate)
Syrup(Vanila)
Syrup(Caramel)
Milk(NormalMilk)
Milk(LowFatMilk)
Milk(NonFatMilk)
Milk(NonLactoseMilk)
drink(latte).
drink(cappuccino).
drink(mocha).
drink(americano).
drink(esspresso).
drinK(caramel_mac).
